# ACME Tenant UI Deployment
# Note: Environment variables are baked into the Docker image at build time using build args.
# The build configuration is specified in values.yaml under tenantUis.acme.buildConfig
# To build tenant-specific images, use:
# docker build --build-arg VUE_APP_TENANT_NAME=acme --build-arg VUE_APP_TITLE="ACME Corporation Portal" ... -t demodeck-tenant-ui:acme-v1.0.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenantUis.acme.name }}
  labels:
    app: {{ .Values.tenantUis.acme.name }}
    chart: {{ include "demodeck-single-version.chart" . }}
    release: {{ .Release.Name }}
    tenant: acme
spec:
  replicas: {{ .Values.tenantUis.acme.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.tenantUis.acme.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tenantUis.acme.name }}
        tenant: acme
    spec:
      securityContext: {}
      containers:
      - name: {{ .Values.tenantUis.acme.name }}
        image: "{{- if .Values.global.registry }}{{ .Values.global.registry }}/{{- end }}{{ .Values.tenantUis.acme.image }}:{{ .Values.tenantUis.acme.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.tenantUis.acme.port }}
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.tenantUis.acme.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.tenantUis.acme.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.tenantUis.acme.resources | nindent 10 }}
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenantUis.acme.name }}-service
  labels:
    app: {{ .Values.tenantUis.acme.name }}
    chart: {{ include "demodeck-single-version.chart" . }}
    release: {{ .Release.Name }}
    tenant: acme
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.tenantUis.acme.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.tenantUis.acme.name }}